services:
  - type: web
    name: vetcare-backend
    env: python
    buildCommand: cd backend-api && pip install -r requirements.txt
    startCommand: cd backend-api && python src/main.py
    envVars:
      - key: SUPABASE_URL
        value: https://[seu-projeto].supabase.co
      - key: SUPABASE_KEY
        value: [sua-service-role-key]
      - key: JWT_SECRET
        value: [seu-segredo]
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: vetcare-frontend
    env: node

    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_URL
        value: https://vetcare-backend.onrender.com
